services:
  mysql:
    image: 'mysql:8.0'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'mysql_data:/var/lib/mysql'
    networks:
      - sail
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-p${DB_PASSWORD}'
      retries: 3
      timeout: 5s

  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin'
    ports:
      - '${FORWARD_PMA_PORT:-8080}:80'
    environment:
      PMA_HOST: mysql
      UPLOAD_LIMIT: 64M
    networks:
      - sail
    depends_on:
      - mysql

networks:
  sail:
    driver: bridge

volumes:
  mysql_data:
    driver: local
